language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm  

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then mkdir -p /home/travis/.phpenv/versions/hhvm/etc/conf.d; fi;
  - phpenv config-add travis/php.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
